"use client";

import {
  AlertDialog,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogAction,
} from "@/components/ui/alert-dialog";
import { useState, useEffect } from "react";

export function Disclaimer() {
  const [showDialog, setShowDialog] = useState(false);

  useEffect(() => {
    setShowDialog(true);
  }, []);

  return (
    <AlertDialog open={showDialog} onOpenChange={setShowDialog}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>Important Disclaimer</AlertDialogTitle>
          <AlertDialogDescription>
            Welcome to DocuInsight! Please note that the summaries and analyses
            provided by our app are generated by AI and are intended for
            informational purposes only. This is not legal advice. If you have
            any concerns or are unsure about any aspect of a document, we
            strongly recommend consulting with a qualified attorney before
            proceeding with signing.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogAction onClick={() => setShowDialog(false)}>
            I Understand
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
