import { tavily } from "@tavily/core";

// Initialize the Tavily client with your API key
const tvly = tavily({ apiKey: process.env.TAVILY_API_KEY });

const options = {
  searchDepth: "advanced", // Determines the thoroughness of the search. Options are:
  // "basic": Standard search with quicker results.
  // "advanced": More comprehensive search with detailed results.
  // Default is "basic" unless specified otherwise. :contentReference[oaicite:0]{index=0}

  topic: "general", // Specifies the category of the search, influencing the search agent used.
  // Options include:
  // "general": Standard search across various topics.
  // "news": Focuses on recent news articles.
  // Default is "general". :contentReference[oaicite:1]{index=1}

  days: 7, // Sets the time frame for search results, looking back a specified number of days.
  // Only applicable when the topic is set to "news".
  // Default is 3 days. :contentReference[oaicite:2]{index=2}

  maxResults: 10, // Limits the maximum number of search results returned.
  // Default is 5. :contentReference[oaicite:3]{index=3}

  includeImages: true, // Indicates whether to include a list of images related to the query in the response.
  // Default is false. :contentReference[oaicite:4]{index=4}

  includeImageDescriptions: true, // When includeImages is true, adds descriptive text for each image.
  // Default is false. :contentReference[oaicite:5]{index=5}

  includeAnswer: true, // Includes a short answer to the original query, generated by an LLM based on Tavily's search results.
  // Default is false. :contentReference[oaicite:6]{index=6}

  includeRawContent: false, // Includes the cleaned and parsed HTML content of each search result.
  // Default is false. :contentReference[oaicite:7]{index=7}

  includeDomains: undefined, // An array of specific domains to include in the search results.
  // Default is undefined, which includes all domains. :contentReference[oaicite:8]{index=8}

  excludeDomains: undefined, // An array of specific domains to exclude from the search results.
  // Default is undefined, which doesn't exclude any domains. :contentReference[oaicite:9]{index=9}

  maxTokens: undefined, // Sets the maximum number of tokens for the response.
  // Default is 4000 tokens. :contentReference[oaicite:10]{index=10}
};

// Record the start time
let startTime = Date.now();

// Perform the search with the specified options
const response = await tvly.search("Who is Leo Messi?", options);

// Calculate the runtime
let runtime = Date.now() - startTime;

// Output the response and runtime
console.log(response);
console.log(`\nRuntime: ${runtime} ms`);
